# ChickenGlide was a joke I've coded during an insomnia...
# I had this idea after replaying to Zelda - Ocarina of Time, and visit the Kakariko village.
# .
# The main feature is to let you carry chicken (right click on it) to glide, but...
# You can also play some games, for example basketball [I suggest velocity from 0.5 to 1],
# or send chicken to other players who have to catch them before they touch the ground...
# .
# You can find the default config file with parameters explained here:
# https://github.com/arboriginal/ChickenGlide/blob/master/src/main/resources/config.yml
# .
# I hope you will have tons of fun with it, and if you make videos, don't hesitate to send me the link:
# I will add them into the plugin description page (with credits to you obviously).
# ........................................................................................ arboriginal
messages: # You can use formatting codes, see https://minecraft.gamepedia.com/Formatting_codes
  config_reloaded: "§8[§6§lChickenGlide§8] §aConfiguration reloaded."
  wrong_item_type: "§cItem you choose for chicken_head.head_item is invalid... Using default."
  easteregg_alert: "§7Something strange happens at §l{x}§7/§l{y}§7/§l{z}§7..." # See easteregg.alert_players
  easteregg_log: |- # Log messages in console
    §8[§6§lChickenGlide§8] §2EasterEgg {event}:
    §b{coords}

# When a player carry a chicken, he temporary get an item (a chicken head by default, suggested by ToasterBorst)
chicken_head:
  player_name: "MHF_Chicken"   # The playername used to generate the chicken head (ignored if item is not "PLAYER_HEAD")
  display_name: "Poor chicken" # Item name the player will see
  head_item: PLAYER_HEAD       # Item used as chicken head (can be for example a feather, suggested by Minestick)
  # Available values: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

limitations:
  max_duration: 120   # Seconds before the effect stops
  baby_chicken: false # If true, you can also use baby chicken
  stop_on_eject: true # If true, the effect stop when the chicken is ejected
  lock_hand: true     # If true, the player cannot change item slot while carrying the chicken
  # in this case, he has to drop it or right click to launch the chicken
  # If false, when the player change his current slot, the chicken flees
  # /!\ I recommend lock hand because some players have a very sentitive mouse wheel, but your choice

behaviors:
  glide_when_carrying: true # If false... You disable the main feature of the plugin...
  # But this has been requested by anoncraftbr who prefers only use the pick up and place features.
  ignore_grass: true        # If true, you can click on a chicken hidden in a grass block without having to cut it
  leave_by_itself: true     # The chicken leave the player shoulder by itself when the effect stops
  change_slot_launch: false # (Only applied when limitations.lock_hand=false)
  # If true,  the chicken is launched when the player change his active slot in his hotbar.
  # If false, the chicken simply flees without velocity (more logic IMHO)
  right_click_launch: true  # If true, on right click you launch the chicken, false: it flees without velocity
  place_when_sneaking: true # If true, whatever you choose for right_click_launch, if the player is sneaking
  # when he right click, the chicken is gently place on the ground instead of launch / flees

  takes_damages:
    enabled: true # If true, the chicken will take damages (trying to escape)
    amount: 0.1   # How many damages the chicken takes
    frequency: 3  # Frequency (seconds) to repeat
  # Note: Damages to chicken are considered as given by the player, so the plugin works well with Revenge
  # https://www.spigotmc.org/resources/revenge-1-7-to-1-14-support.18235/

  eject_velocity: 0.5 # Velocity given to the chicken when the player eject it / 0 to disable
                      # (not applied when the chicken leaves by itself)
                      # High values are fun but less realistic... Your choice! (Chuck Norris = 10)
  # You can use the format « value1;value2 » to use a range. (suggested by LegendDouleB)
  # Example: « 0.1;1.2 » will launch the chicken at a random velocity between 0.1 and 1.2

# By definition, an EasterEgg is not officially documented... So, I let you find what is it :)
# Chance is a multiplicator, not a percentage (values are capped from 0.01 to 100 when the config is read).
# You should disable it on serious (earnest) servers, because it's something totally nutty (and useless).
easteregg:
  enabled: true
  chance: 1
  log_events: true
  alert_players: true